const stickersDataList = [
    {
        title:"tomAndJerry",
        id:1,
        tabImageUri:require("../assets/images/Stickers/thumbnail/pngwing.com.png"),
        stickers:[
            {id:1,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/3-1.thumb128.png"},
            {id:2,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/5-1.thumb128.png"},
            {id:3,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/15-1.thumb128.png"},
            {id:4,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/8-1.thumb128.png"},
            {id:5,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/12-1.thumb128.png"},
            {id:6,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/29-1.thumb128.png"},
            {id:7,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/33-1.thumb128.png"},
            {id:8,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/25-1.thumb128.png"},
            {id:9,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/18-1.thumb128.png"},
            {id:10,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/39-1.thumb128.png"},
        ]
    },
    {
        title:"tomAndJerryd",
        id:2,
        tabImageUri:require("../assets/images/Stickers/thumbnail/pngwing.com.png"),
        stickers:[
            {id:1,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/3-1.thumb128.png"},
            {id:2,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/5-1.thumb128.png"},
            {id:3,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/15-1.thumb128.png"},
            {id:4,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/8-1.thumb128.png"},
            {id:5,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/12-1.thumb128.png"},
            {id:6,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/29-1.thumb128.png"},
            {id:7,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/33-1.thumb128.png"},
            {id:8,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/25-1.thumb128.png"},
            {id:9,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/18-1.thumb128.png"},
            {id:10,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/39-1.thumb128.png"},
        ]
    },
    {
        title:"tomAndJerryfg",
        id:3,
        tabImageUri:require("../assets/images/Stickers/thumbnail/pngwing.com.png"),
        stickers:[
            {id:1,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/3-1.thumb128.png"},
            {id:2,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/5-1.thumb128.png"},
            {id:3,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/15-1.thumb128.png"},
            {id:4,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/8-1.thumb128.png"},
            {id:5,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/12-1.thumb128.png"},
            {id:6,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/29-1.thumb128.png"},
            {id:7,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/33-1.thumb128.png"},
            {id:8,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/25-1.thumb128.png"},
            {id:9,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/18-1.thumb128.png"},
            {id:10,fileUri:"https://storage.googleapis.com/sticker-prod/tvBuhSfw4MV2IxN1I7Z3/39-1.thumb128.png"},
        ]
    }
];

export {stickersDataList}