const ThemesDataList = [
    {
        name:"theme_1",
        image:require("./../assets/images/themes/theme1.jpg"),
        topBarBg:"#E5DBFB",
        topBarTitleColor:"#000000",
        topBarIconColor:"#663EB4",
        bottonBarBg:"#E5DBFB",
        bottomBarIconColor:"#663EB4",
        addDiaryBtnBg:"#663EB4",
        addDiaryIconColor:"#FFFFFF",
        buttonBg:"#BFA4F4",
        buttonTextColor:"#000000",
        bodyBgColor:"#F2EDFD",
        calendarCurrentBG:"#8673AB",
        calendarSelectedDayBG:"#D9C8F8"
    },
    {
        name:"theme_2",
        image:require("./../assets/images/themes/theme2.jpg"),
        topBarBg:"#023859",
        topBarTitleColor:"#ffffff",
        topBarIconColor:"#ffffff",
        bottonBarBg:"#276A93",
        bottomBarIconColor:"#ffffff",
        addDiaryBtnBg:"#478AAD",
        addDiaryIconColor:"#ffffff",
        buttonBg:"#6593A6",
        buttonTextColor:"#ffffff",
        bodyBgColor:"#C5D7D9",
    },
    // {
    //     name:"theme_3",
    //     image:require("./../assets/images/themes/theme3.jpg"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_4",
    //     image:require("./../assets/images/themes/theme4.jpg"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_5",
    //     image:require("./../assets/images/themes/theme5.jpg"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_6",
    //     image:require("./../assets/images/themes/theme6.jpg"),
    //     topBarBg:"#60A672",
    //     topBarTitleColor:"#FFFFFF",
    //     topBarIconColor:"#FFFFFF",
    //     bottonBarBg:"#69BFAF",
    //     bottomBarIconColor:"#FFFFFF",
    //     addDiaryBtnBg:"#F2DC6B",
    //     addDiaryIconColor:"#000000",
    //     buttonBg:"#80C3AD",
    //     buttonTextColor:"#000000",
    //     bodyBgColor:"#F2D5D5",
    // },
    // {
    //     name:"theme_7",
    //     image:require("./../assets/images/themes/theme7.jpg"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_8",
    //     image:require("./../assets/images/themes/theme8.jpg"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_9",
    //     image:require("./../assets/images/themes/theme9.png"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_10",
    //     image:require("./../assets/images/themes/theme10.png"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_11",
    //     image:require("./../assets/images/themes/theme11.png"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_12",
    //     image:require("./../assets/images/themes/theme12.png"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
    // {
    //     name:"theme_13",
    //     image:require("./../assets/images/themes/theme13.png"),
    //     topBarBg:"",
    //     topBarTitleColor:"",
    //     topBarIconColor:"",
    //     bottonBarBg:"",
    //     bottomBarIconColor:"",
    //     addDiaryBtnBg:"",
    //     addDiaryIconColor:"",
    //     buttonBg:"",
    //     buttonTextColor:"",
    //     bodyBgColor:"",
    // },
];

export default ThemesDataList;